### PR TITLE
New parameter to disable auto-hilighting on first choice

### PR DESCRIPTION
**Pull request by superzazu**
fixes #443 (https://github.com/yourlabs/django-autocomplete-light/issues/443)

### CODE REVIEW

**Comment by blueyed** [comment]
This seems to only change the highlighting, but not the selection (i.e. what would happen on pressing Enter), right?

**Comment by superzazu** [comment]
If autoHilightFirst = false and the user presses enter, the form is submitted, like any regular HTML form.
If autoHilightFirst = true (default), the bavahiour stays the same as before.

**Comment by jpic** [comment]
If there's a BC break then DAL tests will spot them.

Could you please rebase your commits and make only one commit for this ? Thanks !

**Comment by jpic** [comment]
It's a bit of a problem that we don't have proper unit tests in this repo ... should not be so hard to do thought.

**Comment by superzazu** [comment]
@jpic, I squashed my commits into one.

**Pull request merged**
